### ISSUE TITLE
RuntimeError when train

### ISSUE THREAD

**Issue by administrator2992** [SilvesterYu/YOLO_Silvey_Task#1]
get error RuntimeError: result type Float can't be cast to the desired output type long int when train with [train.py](https://github.com/SilvesterYu/YOLO_Silvey_Task/blob/main/yolov5copy/train.py). If I run [train.py](https://github.com/SilvesterYu/YOLO_Silvey_Task/blob/main/yolov5copy/train.py) so bounding box annotation will convert to ellipse annotation right ? or something else step ?

**Comment by SilvesterYu** [comment]
are you using torch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 exactly?

**Comment by administrator2992** [comment]
Oh, last work I used colab but torch 1.10.1 imcopatible with torchtext 0.15.1. But now is not problem, we will see again in the training section. thank you the response
